# Site settings
author: Kyle Smith
title: Somewhere between Infinity War and Hotel Transylvania 
header-img: img/home-bg.png
email: kylemclellan@gmail.com
copyright_name: Kyle Smith
description: > # this means to ignore newlines until "baseurl:"
   
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  springHeeledHack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
